// <auto-generated />
using System;
using Ao3Tracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ao3Tracker.Api.Data.Migrations.Postgres
{
    [DbContext(typeof(PostgresAppDbContext))]
    partial class PostgresAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ao3Tracker.Api.Models.Ao3Credential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ao3Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EncryptedSessionCookie")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SessionEstablishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SessionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Ao3Credentials");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Ao3Pseud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PseudName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.HasIndex("Username", "PseudName")
                        .IsUnique();

                    b.ToTable("Ao3Pseuds");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Ao3Series", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.ToTable("Ao3Series");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Download", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<byte>("Format")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkDownloadFileId")
                        .HasColumnType("integer");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkDownloadFileId");

                    b.HasIndex("WorkId");

                    b.HasIndex("UserId", "WorkId", "Format")
                        .IsUnique();

                    b.ToTable("Downloads");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.ScrapeJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("interval");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScraperKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "NextRunAt");

                    b.ToTable("ScrapeJobs");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.ScrapeRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("FirstPageFetched")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HitRequestCap")
                        .HasColumnType("boolean");

                    b.Property<bool>("HitTimeCap")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastPageFetched")
                        .HasColumnType("integer");

                    b.Property<byte>("Mode")
                        .HasColumnType("smallint");

                    b.Property<int>("PagesFetched")
                        .HasColumnType("integer");

                    b.Property<int>("ParseWarnings")
                        .HasColumnType("integer");

                    b.Property<int>("RequestsMade")
                        .HasColumnType("integer");

                    b.Property<int>("ScrapeJobId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StopReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WorksAdded")
                        .HasColumnType("integer");

                    b.Property<int>("WorksSeen")
                        .HasColumnType("integer");

                    b.Property<int>("WorksUpdated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("ScrapeJobId", "StartedAt");

                    b.ToTable("ScrapeRuns");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("Ao3TagId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("BackfillBeforeUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BackfillCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("BackfillMinUpdatedAtSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BackfillNextPage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("BackfillStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("BackfillState")
                        .HasColumnType("smallint");

                    b.Property<string>("CanonicalTagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CanonicalTagNameNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("IncrementalWatermarkUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFullSweepCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFullSweepStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastIncrementalRunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LastKnownTotalWasAuthenticated")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastKnownTotalWorks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastKnownTotalWorksAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextVerificationAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TagId")
                        .HasColumnType("integer");

                    b.Property<string>("TagUrlSegment")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("VerificationAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("VerificationCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VerificationError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte>("VerificationState")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Ao3TagId");

                    b.HasIndex("CanonicalTagNameNormalized")
                        .IsUnique();

                    b.HasIndex("TagId");

                    b.HasIndex("VerificationState", "NextVerificationAttemptAt");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.ShipWork", b =>
                {
                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MissingSinceAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ShipId", "WorkId");

                    b.HasIndex("WorkId");

                    b.HasIndex("ShipId", "LastSeenAt");

                    b.ToTable("ShipWorks");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("Ao3TagId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Ao3TagId");

                    b.HasIndex("Type", "NameNormalized")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.UserWorkState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.HasIndex("UserId", "Rating");

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("UserId", "WorkId")
                        .IsUnique();

                    b.ToTable("UserWorkStates", t =>
                        {
                            t.HasCheckConstraint("CK_UserWorkStates_Rating", "\"Rating\" IS NULL OR (\"Rating\" >= 1 AND \"Rating\" <= 10)");
                        });
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.WatchedShip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayNameOverride")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestedTagName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.HasIndex("UserId", "ShipId")
                        .IsUnique();

                    b.ToTable("WatchedShips");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Work", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Bookmarks")
                        .HasColumnType("integer");

                    b.Property<int>("Categories")
                        .HasColumnType("integer");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("integer");

                    b.Property<int>("CollectionCount")
                        .HasColumnType("integer");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DetailFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Hits")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kudos")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("LanguageName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastScrapedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PlannedChapterCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("SummaryHtml")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UpdatedAtIsApproximate")
                        .HasColumnType("boolean");

                    b.Property<int>("Warnings")
                        .HasColumnType("integer");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Bookmarks");

                    b.HasIndex("CommentCount");

                    b.HasIndex("Hits");

                    b.HasIndex("IsComplete");

                    b.HasIndex("Kudos");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("Rating");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("WordCount");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.WorkAuthor", b =>
                {
                    b.Property<long>("WorkId")
                        .HasColumnType("bigint");

                    b.Property<int>("PseudId")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("WorkId", "PseudId");

                    b.HasIndex("PseudId");

                    b.ToTable("WorkAuthors");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.WorkDownloadFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Format")
                        .HasColumnType("smallint");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("WorkUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "Format", "WorkUpdatedAt")
                        .IsUnique();

                    b.ToTable("WorkDownloadFiles");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.WorkSeries", b =>
                {
                    b.Property<long>("WorkId")
                        .HasColumnType("bigint");

                    b.Property<long>("SeriesId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Part")
                        .HasColumnType("integer");

                    b.HasKey("WorkId", "SeriesId");

                    b.HasIndex("SeriesId");

                    b.ToTable("WorkSeries");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.WorkTag", b =>
                {
                    b.Property<long>("WorkId")
                        .HasColumnType("bigint");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("WorkId", "TagId");

                    b.HasIndex("TagId", "WorkId");

                    b.ToTable("WorkTags");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Ao3Credential", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.ApplicationUser", "User")
                        .WithOne("Ao3Credential")
                        .HasForeignKey("Ao3Tracker.Api.Models.Ao3Credential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Download", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.ApplicationUser", "User")
                        .WithMany("Downloads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ao3Tracker.Api.Models.WorkDownloadFile", "File")
                        .WithMany()
                        .HasForeignKey("WorkDownloadFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ao3Tracker.Api.Models.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("User");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.ScrapeJob", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.ScrapeRun", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.ScrapeJob", "ScrapeJob")
                        .WithMany("Runs")
                        .HasForeignKey("ScrapeJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrapeJob");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Ship", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.ShipWork", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.Ship", "Ship")
                        .WithMany("Works")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ao3Tracker.Api.Models.Work", "Work")
                        .WithMany("Ships")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.UserWorkState", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.ApplicationUser", "User")
                        .WithMany("WorkStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ao3Tracker.Api.Models.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.WatchedShip", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.Ship", "Ship")
                        .WithMany("Watchers")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ao3Tracker.Api.Models.ApplicationUser", "User")
                        .WithMany("WatchedShips")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.WorkAuthor", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.Ao3Pseud", "Pseud")
                        .WithMany("Works")
                        .HasForeignKey("PseudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ao3Tracker.Api.Models.Work", "Work")
                        .WithMany("Authors")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pseud");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.WorkDownloadFile", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.WorkSeries", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.Ao3Series", "Series")
                        .WithMany("Works")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ao3Tracker.Api.Models.Work", "Work")
                        .WithMany("Series")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.WorkTag", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.Tag", "Tag")
                        .WithMany("Works")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ao3Tracker.Api.Models.Work", "Work")
                        .WithMany("Tags")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ao3Tracker.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ao3Tracker.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Ao3Pseud", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Ao3Series", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.ApplicationUser", b =>
                {
                    b.Navigation("Ao3Credential");

                    b.Navigation("Downloads");

                    b.Navigation("WatchedShips");

                    b.Navigation("WorkStates");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.ScrapeJob", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Ship", b =>
                {
                    b.Navigation("Watchers");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Tag", b =>
                {
                    b.Navigation("Works");
                });

            modelBuilder.Entity("Ao3Tracker.Api.Models.Work", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Series");

                    b.Navigation("Ships");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
