using Ao3Tracker.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Ao3Tracker.Api.Data.Configurations;

public class WorkConfiguration : IEntityTypeConfiguration<Work>
{
    public void Configure(EntityTypeBuilder<Work> entity)
    {
        entity.HasKey(w => w.Id);

        // The id comes from AO3, never from the database. Without this SQLite would declare the
        // column AUTOINCREMENT and PostgreSQL GENERATED BY DEFAULT AS IDENTITY; inserting real
        // AO3 ids would then leave the Postgres sequence far behind the data, and the first
        // database-generated id would collide with an existing row.
        entity.Property(w => w.Id).ValueGeneratedNever();

        entity.Property(w => w.Title).HasMaxLength(512).IsRequired();
        entity.Property(w => w.LanguageCode).HasMaxLength(16);
        entity.Property(w => w.LanguageName).HasMaxLength(64);

        // Filter/sort columns for the library view. Write amplification is irrelevant here:
        // the rate limiter caps ingest at roughly three rows per second.
        entity.HasIndex(w => w.UpdatedAt);
        entity.HasIndex(w => w.Kudos);
        entity.HasIndex(w => w.Hits);
        entity.HasIndex(w => w.Bookmarks);
        entity.HasIndex(w => w.CommentCount);
        entity.HasIndex(w => w.WordCount);
        entity.HasIndex(w => w.Rating);
        entity.HasIndex(w => w.IsComplete);
        entity.HasIndex(w => w.LanguageCode);
        entity.HasIndex(w => w.LastSeenAt);
    }
}

public class TagConfiguration : IEntityTypeConfiguration<Tag>
{
    public void Configure(EntityTypeBuilder<Tag> entity)
    {
        entity.HasKey(t => t.Id);

        entity.Property(t => t.Name).HasMaxLength(200).IsRequired();
        entity.Property(t => t.NameNormalized).HasMaxLength(200).IsRequired();

        // Uniqueness and lookup both go through the normalized column — never through Name,
        // whose comparison semantics differ between SQLite and PostgreSQL.
        entity.HasIndex(t => new { t.Type, t.NameNormalized }).IsUnique();
        entity.HasIndex(t => t.Ao3TagId);
    }
}

public class WorkTagConfiguration : IEntityTypeConfiguration<WorkTag>
{
    public void Configure(EntityTypeBuilder<WorkTag> entity)
    {
        entity.HasKey(wt => new { wt.WorkId, wt.TagId });

        entity.HasOne(wt => wt.Work)
            .WithMany(w => w.Tags)
            .HasForeignKey(wt => wt.WorkId)
            .OnDelete(DeleteBehavior.Cascade);

        entity.HasOne(wt => wt.Tag)
            .WithMany(t => t.Works)
            .HasForeignKey(wt => wt.TagId)
            .OnDelete(DeleteBehavior.Cascade);

        // Reverse direction: "every work carrying this tag".
        entity.HasIndex(wt => new { wt.TagId, wt.WorkId });
    }
}

public class Ao3PseudConfiguration : IEntityTypeConfiguration<Ao3Pseud>
{
    public void Configure(EntityTypeBuilder<Ao3Pseud> entity)
    {
        entity.HasKey(p => p.Id);

        entity.Property(p => p.Username).HasMaxLength(100).IsRequired();
        entity.Property(p => p.PseudName).HasMaxLength(100).IsRequired();
        entity.Property(p => p.UsernameNormalized).HasMaxLength(100).IsRequired();
        entity.Property(p => p.PseudNameNormalized).HasMaxLength(100).IsRequired();
        entity.Property(p => p.DisplayName).HasMaxLength(200).IsRequired();
        entity.Property(p => p.DisplayNameNormalized).HasMaxLength(200).IsRequired();

        // Unique on the normalized pair, not the rendered one: AO3 bylines vary in case, and a
        // unique key over the raw columns lets the same creator become two rows — which is how a
        // work ends up listed under an author the library then treats as a stranger.
        entity.HasIndex(p => new { p.UsernameNormalized, p.PseudNameNormalized }).IsUnique();
        entity.HasIndex(p => p.UsernameNormalized);

        // Author search goes through the normalized column, never DisplayName — see Tag.
        entity.HasIndex(p => p.DisplayNameNormalized);
    }
}

public class WorkAuthorConfiguration : IEntityTypeConfiguration<WorkAuthor>
{
    public void Configure(EntityTypeBuilder<WorkAuthor> entity)
    {
        entity.HasKey(wa => new { wa.WorkId, wa.PseudId });

        entity.HasOne(wa => wa.Work)
            .WithMany(w => w.Authors)
            .HasForeignKey(wa => wa.WorkId)
            .OnDelete(DeleteBehavior.Cascade);

        entity.HasOne(wa => wa.Pseud)
            .WithMany(p => p.Works)
            .HasForeignKey(wa => wa.PseudId)
            .OnDelete(DeleteBehavior.Cascade);

        entity.HasIndex(wa => wa.PseudId);
    }
}

public class Ao3SeriesConfiguration : IEntityTypeConfiguration<Ao3Series>
{
    public void Configure(EntityTypeBuilder<Ao3Series> entity)
    {
        entity.HasKey(s => s.Id);
        entity.Property(s => s.Id).ValueGeneratedNever();   // AO3's series id — see WorkConfiguration
        entity.Property(s => s.Title).HasMaxLength(512).IsRequired();
    }
}

public class WorkSeriesConfiguration : IEntityTypeConfiguration<WorkSeries>
{
    public void Configure(EntityTypeBuilder<WorkSeries> entity)
    {
        entity.HasKey(ws => new { ws.WorkId, ws.SeriesId });

        entity.HasOne(ws => ws.Work)
            .WithMany(w => w.Series)
            .HasForeignKey(ws => ws.WorkId)
            .OnDelete(DeleteBehavior.Cascade);

        entity.HasOne(ws => ws.Series)
            .WithMany(s => s.Works)
            .HasForeignKey(ws => ws.SeriesId)
            .OnDelete(DeleteBehavior.Cascade);

        entity.HasIndex(ws => ws.SeriesId);
    }
}
